### ISSUE TITLE
Ability to change colors?

### ISSUE THREAD

**Issue by cedricve** [angelodlfrtr/go-invoice-generator#12]
Awesome work! Would it be possible to tweak the colors within the PDF being generated.

**Comment by leucos** [comment]
You probably can do somthing around here https://github.com/angelodlfrtr/go-invoice-generator/blob/master/constants.go#L64-L73

**Comment by angelodlfrtr** [comment]
Hey, now possible in v0.3.0 via Options : https://github.com/angelodlfrtr/go-invoice-generator/blob/5b026649f3cd16316958c4f2dbe0132dd33bb29b/options.go#L34-L37

**Comment by cedricve** [comment]
I would suggest "white" as well..
