### ISSUE TITLE
Unicode encoding doesn't work

### ISSUE THREAD

**Issue by microo8** [angelodlfrtr/go-invoice-generator#14]
I must generate some invoices with non-english characters and the output doesn't encode it correctly.

This is just a test with some random strings like "ČŤŽÝ" and "šýžč 18". 

![invoice](https://i.ibb.co/8Nw21W8/screen.png)

**Comment by angelodlfrtr** [comment]
Hello,

You can fin an example implementation with special characters in the latest tag : https://github.com/angelodlfrtr/go-invoice-generator/tree/v0.3.1/examples/iso_8859_2_cp

You will need to adapt the code page used by gofpdf, see https://github.com/jung-kurt/gofpdf/tree/master/font for list of supported code pages and https://github.com/jung-kurt/gofpdf/issues/199#issuecomment-428520606 for explanation.
