### ISSUE TITLE
[FEATURE REQUEST] - Marshal and Unmarshal built doc for storing as byte

### ISSUE THREAD

**Issue by sujit-baniya** [angelodlfrtr/go-invoice-generator#15]
Is it possible to Marshal the pdf doc to byte and store in database. And later we just unmarshal the bytes to show to user or download?

**Comment by angelodlfrtr** [comment]
Hello,

yes, just added an example here : https://github.com/angelodlfrtr/go-invoice-generator/blob/master/examples/bytes/main.go#L107
