### ISSUE TITLE
Extend Contact field, Add legal field

### ISSUE THREAD

**Issue by lsorba** [angelodlfrtr/go-invoice-generator#20]
Hi, first of all thank you for your nice work!

I started to integrate your lib and found out that some important fields were missing for my invoices.

I would like to add more fields to the contacts, like a phone number, a taxId, a companyId
and also some legal text, like bank details, or overdue penalties or VAT exemptions,...
Some of them are mandatory for businesses.

Do you see a way for me to extend the Contact/Company to my needs with the existing ? and also add a 'legal box' for the legal texts ?
Or is it planned to make the lib more flexible ?

Thanks

**Comment by angelodlfrtr** [comment]
Hi @lsorba, thanks you !

Yes, your request is similar to #13.

My idea is to convert `Contact` to an interface wich must contain a `Render(*Document)` function and a `DefaultContact` struct with current `Contact` fields implementation.

So you can implement your own `Contact` interface with your custom fields and custom rendering logic.

For the moment if you want to implement your custom fields you can fork the repo, I will try to take time in the next few days to implement this.

**Comment by lsorba** [comment]
Hi @angelodlfrtr, thank you for your answer.

Interfaces for the contacts sound good! I managed to write the legal text in the `Notes` with some formatting,
I was using the closing tag `<br/>` instead of `<br>` now I can format it as I wanted.

**Comment by angelodlfrtr** [comment]
Hi @lsorba,

I just added a `AdditionnalInfo` field to `Contact` string which is a string slice 3407e5015e643155020c372a67fac8a871e839d5.
Each line is appended after the contact block so you can pass arbitrary text.
