### ISSUE TITLE
Is there an error in discountPercent Calculation inside the Tax method (totals.go)

### ISSUE THREAD

**Issue by jshiwam** [angelodlfrtr/go-invoice-generator#21]
https://github.com/angelodlfrtr/go-invoice-generator/blob/master/totals.go#L60

On this line we calculate the discountPercent as follows:

`discountPercent = discountAmount.Mul(decimal.NewFromFloat(100)).Div(totalWithoutTax)`

here we have already subtracted document.Discount from `doc.TotalWithoutTaxAndWithoutDocumentDiscount()` which gives us `totalWithoutTax`.

Shouldn't we perform the calculation as follows?
`discountPercent = discountAmount.Mul(decimal.NewFromFloat(100)).Div(doc.TotalWithoutTaxAndWithoutDocumentDiscount())`

Test Case:
```
TotalWithoutTaxAndWithoutDocumentDiscount(Only applied item's discount not the document discount)
1. 50
2. 50

Tax %
1. 2%
2. 3%

discountAmount = 40(DiscountType="amount")
totalWithouTax (sum(TotalWithoutTaxAndWithoutDocumentDiscount)-discountAmount)= 100-40 = 60
Calculate Discount %:
Current Formula: discountAmount.Mul(decimal.NewFromFloat(100)).Div(totalWithoutTax) = 40*100/60 ~ 67%
Proposed Formula: discountAmount.Mul(decimal.NewFromFloat(100)).Div(doc.TotalWithoutTaxAndWithoutDocumentDiscount()) = 40*100/100 = 40%

TotalTax Calculation:

// Else, remove doc discount % from item total without tax and item discount
itemTotal := item.TotalWithoutTaxAndWithDiscount()
toSub := discountPercent.Mul(itemTotal).Div(decimal.NewFromFloat(100))
itemTotalDiscounted := itemTotal.Sub(toSub)

itemTotal
1. 50
2. 50

toSub(discount%=67%)
1. 67*50/100=33.5
2. 67*50/100=33.5
TotalDiscountedAmount = 33.5*2=67

toSub(discount%=40%)
1. 40*50/100=20
2. 40*50/100=20
TotalDiscountedAmount = 20*2=40

```
I think there is an error while calculating the discount% which needs to be changed, as suggested in this post

**Comment by angelodlfrtr** [comment]
Hi @jshiwam,

Thank you very much for pointing out this problem, you are right the calculation was wrong.
Just fixed in commit [3498a76](https://github.com/angelodlfrtr/go-invoice-generator/commit/3498a76aeb971c3d439dc88ac2b5bd2d67023f4c).
