### ISSUE TITLE
Multi Lines Notes

### ISSUE THREAD

**Issue by vHanda** [angelodlfrtr/go-invoice-generator#23]
Hi. I'd like to use this to add payment information. What specific bank account + routing number + other info regard how this invoice should be paid. The only place I found I could add that was in the "notes" section.

I've tried adding a large multi line string, but it gets compressed into a single line and is difficult to read and understand.

Is there some way I can add some long free form text to the invoice?

Eg - 

```
Payment to be made in "USD".

Account holder: xxx xxx
ACH and Wire routing number: xxx
Account number: xxx
Account type: Checking
Wise's address: 30 W. 26th Street, Sixth Floor
New York NY 10010
United States
```

becomes 

```
Payment to be made in "USD". Account holder: X X ACH
and Wire routing number: xxxxxxxx Account number: xxxxxxxxx
Account type: Checking Wise's address: 30 W. 26th Street, Sixth
Floor New York NY 10010 United States
```

**Comment by mikigatto93** [comment]
Have you tried forcing the line breaks with <br>?

**Comment by mikigatto93** [comment]
Have you tried forcing the line breaks with `<br>` ?

**Comment by vHanda** [comment]
Thanks. That works perfectly.

I'm not sure why I didn't think of it.
